// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © udayadds

strategy(title="ORB study", overlay=true, default_qty_type = strategy.percent_of_equity, default_qty_value = 3)
up5on = input(true, title="5 mins orb high")
down5on = input(true, title="5 mins orb low")

is_newbar(res)=>
    change(time(res)) != 0
    
adopt(r, s)=>
    security(tickerid, r, s)
    
high_range = valuewhen(is_newbar("D"), high, 0)
low_range = valuewhen(is_newbar("D"), low, 0)

adopt_1 = adopt('60', high_range)
up5 = plot(adopt_1, title="high", color=#009911, linewidth=1)

adopt_2 = adopt('60', low_range)
down5 = plot(adopt_2, title="low", color=#ff0000, linewidth=1)

rsi = rsi(close, 14)
smaVol = sma(volume, 20)


strategy.entry(id="long", long=true, when=close>adopt_1 && rsi>60)
strategy.close(id="long", when=close<adopt_2)
strategy.entry(id="short", long=false, when=close<adopt_2 && rsi<40)
strategy.close(id="short", when=close>adopt_1)
